### ISSUE TITLE
Usage Example

### ISSUE THREAD

**Issue by jamescarter-le** [Bella-DeFinTech/uniswap-v3-simulator#50]
Hello Team,

This tool looks exceptionally useful, I am producing components on Nethereum for integrating with UniswapV3, and was looking for a way to simulate Positions, your tool would be amazing to use.

Do you have any usage examples?

I can see the intent is to stream in events into the Library some how, after configuring a pool. You have checked in some DBs to get started,  but do you have a Gist or similar of a basic usage?

Create Pool
Stream Events
Get Positions/Pool State
Exit

```
var client = await SimulatorClient.buildInstance();
var configurablePool = client.initCorePoolFromConfig(
    SimulatorClient.buildPoolConfig(60, "USDC", "ETH", FeeAmount.MEDIUM)
);

let sqrtPriceX96ForInitialization = JSBI.BigInt("4295128739");
await configurablePool.initialize(sqrtPriceX96ForInitialization);
let pools = await client.simulatorRoadmapManager.listRoutes();
console.log(pools); // <-- We have a Pool

for(var OneEvent in AllMyEvents)
{
    configurablePool.PushEventIntoPool(OneEvent)
    var myFees = configurablePool.Posititions.MyPosition.feeGrowthInside0X128;
    console.log('My Stacks: ' + myFees);
}
```

**Comment by neptune-v** [comment]
Hi @jamescarter-le , thanks for the interest in our tool! 
And sorry for the lack of documentation at the moment, we are working on finalizing some abstraction layers and packaging stuff then finishing off the docs.

Here is a full example of how to run a backtest of a placeholder strategy (standard deviation in this example):
https://github.com/Bella-DeFinTech/uniswap-v3-bot/blob/main/test/Backtest.test.ts

This includes the following steps:

1. Using mainnet data to initialize a core pool
2. Replaying events
3. Running strategy to decide whether an adjustment of price range should be done
4. Replaying the next events



Also, for downloading mainnet data, we had to pre-process the data because mainnet events of swaps only represent the results of the swap, we had to use a try-and-error logic to test out the actual inputs of that swap. 

This means, there is more information added on top of the mainnet events, and this extra information (correct inputs of the swap that emit the event recorded on mainnet) is only added during the download process.

And here is the download script for that:

https://github.com/Bella-DeFinTech/uniswap-v3-simulator/blob/dev/scripts/Events.ts

Let me know if this is helpful to your question, please let us know if you need more help on the details.

Thanks!!

**Comment by neptune-v** [comment]
We are also thinking about downloading events from subgraph, but for now, you will need to use hardhat+ether.js, meaning some setup of a RPC provider etc.

**Comment by jamescarter-le** [comment]
Thank you so much for your thorough response @neptune-v 

I really appreciate the time spent explaining the functionality, I'm quite happy finding the events either with your script or with my own application to feed the Tuner.

This will save me a lot of time, and help validate my application before it is released on mainnet. Thank you very much for making this available to the public.

**Comment by rkedia145** [comment]
Hi @neptune-v and team, thank you so much for creating this tool! Quick question: 

In the Events.ts script, the '// await saveEvents(EventType.SWAP, fromBlock, endBlock);' is commented out. Why is this? Is the script not yet ready to save swap events?

**Comment by neptune-v** [comment]
> Hi @neptune-v and team, thank you so much for creating this tool! Couple of questions:
> 
> 2. I notice that in ConfigurableCorePool.test.ts, the lines for 'swapEventDB.addAmountSpecified'. Is this step no longer necessary?

Please refer to the answer above, we commented out that section of code because it was a one-time thing, after the data has been pre-processed it is no longer needed, so we commented them out. If you want to download and pre-process the data for the first time then follow the instructions above.

@kafeikui could you please take a look at the first question?

**Comment by kafeikui** [comment]
> Hi @neptune-v and team, thank you so much for creating this tool! Couple of questions:
> 
> 1. In the Events.ts script, the '// await saveEvents(EventType.SWAP, fromBlock, endBlock);' is commented out. Why is this? Is the script not yet ready to save swap events?
> 2. I notice that in ConfigurableCorePool.test.ts, the lines for 'swapEventDB.addAmountSpecified'. Is this step no longer necessary?

Hi @rkedia145 , thanks for the attention!
1. It's ok to save swap events. What you see here is the setup we used last time for updating events. Since we don't want to miss or have duplicate of swap events or liquidity events(mint/burn), we set the block number of latest swap events we downloaded before, then commented it out and did the same to liquidity events.

I just realize the updating process can be done at one batch with the same startBlock and it won't get influenced by different block height of the latest 3 types of events. So just uncomment that line and download the swap events if you want. Thanks for reminding that!

2. There is a difference between parameters of swap function and swap event. Those lines are served for pre-process of swap events after we downloaded them. Then we can use the swap record as input of swap function. I think you may find the answer by @neptune-v above helpful too. The commented lines is some leftover during our test. We don't want that to be generated repeatedly because one run of pre-process costs several minutes(it depends on events count actually). After saving a pre-processed database, we commented these lines out to save the time for unit tests.

We are still doing the final wrap up work before publishing a package, where we will put in clearer API and more specific documentation, including readable usage example. Thanks for the interest again and please stay tuned!

**Comment by rkedia145** [comment]
Hi @neptune-v, @kafeikui , 

Thanks for the detailed responses! One more followup:

I understand what you mean about how 'swapEventDB.addAmountSpecified' is a one time pre-processing step (my understanding is that essentially the parameters of the swap event, namely amount0 and amount1, will not precisely line up with the original amountSpecified that was passed into the swap function, so you do a trial-and-error approach to figure out which value of amountSpecified results in the amount0 and amount1 seen on the event, correct?). 

However, after the 'amount_specified' is saved to the DB, and that line is commented out, I don't actually see where amount_specified is being used again. In the current ConfigurableCorePool.test.ts, when tryWithDryRun and trySwap are called, it is still passing in either param.amount0, or param.amount1, not param.amountSpecified. Could you please clarify if this is the correct behavior?

**Comment by rkedia145** [comment]
@neptune-v @kafeikui ah I just found the answer to my question. The amountSpecified is not used in the v3-simulator, but in the v3-bot. Thanks!
